version: '2'
services:
    dpaasauth-app:
        image: dpaasauth
        external_links:
            - dpaasauth-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dpaasauth?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dpaasauth-mysql:
        extends:
            file: mysql.yml
            service: dpaasauth-mysql
